<?php

declare(strict_types=1);

namespace BAGArt\TelegramBot\Outbound;

use JsonSerializable;
use RuntimeException;

/**
 * Outbound task envelope: immutable payload + mutable state + delivery ID.
 *
 * $deliveryId is populated during {@see OutboundQueueContract::pop()} and identifies
 * a specific in-flight record (for ack / renewLease). NOT serialized to queue —
 * generated by the adapter on each pop to prevent worker cross-talk.
 */
final class OutboundEnvelope implements JsonSerializable
{
    /**
     * @param  OutboundTask  $task  Immutable task payload.
     * @param  OutboundTaskState  $state  Mutable state (attempts, status, error).
     * @param  string|null  $deliveryId  In-flight identifier (after pop only), null in queue.
     */
    public function __construct(
        public readonly OutboundTask $task,
        public OutboundTaskState $state,
        public ?string $deliveryId = null,
    ) {
    }

    public function jsonSerialize(): array
    {
        return [
            'task' => $this->task->jsonSerialize(),
            'state' => $this->state->jsonSerialize(),
        ];
    }

    /**
     * @param  array<string,mixed>  $data  Result of jsonSerialize() (without deliveryId).
     *
     * @throws RuntimeException If the format is not recognized.
     */
    public static function fromJson(array $data): self
    {
        $schemaVersion = $data['schemaVersion'] ?? 1;

        return match ($schemaVersion) {
            1 => self::fromJsonV1($data),
            default => throw new RuntimeException("Unsupported OutboundEnvelope schemaVersion: {$schemaVersion}"),
        };
    }

    /**
     * @param  array<string,mixed>  $data
     */
    private static function fromJsonV1(array $data): self
    {
        return new self(
            task: OutboundTask::fromJson((array) $data['task']),
            state: OutboundTaskState::fromArray((array) $data['state']),
        );
    }
}
